Updated files
Signed-off-by: alvaropicazo <alvaro.picazo.haase@accenture.com>

diff --git a/platforms/quorum/charts/crypto_ibft/templates/job.yaml b/platforms/quorum/charts/crypto_ibft/templates/job.yaml
--- a/platforms/quorum/charts/crypto_ibft/templates/job.yaml
+++ b/platforms/quorum/charts/crypto_ibft/templates/job.yaml
@@ -24,7 +24,7 @@ spec:
         - name: {{ $.Values.vault.imagesecretname }}
       securityContext:
         fsGroup: 1000        
-      containers:
+      initContainers:
       - name: crypto-init
         image: {{ $.Values.image.initContainerName }}
         imagePullPolicy: Always
@@ -71,9 +71,7 @@ spec:
 
           KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
           echo "Getting secrets from Vault Server: ${VAULT_ADDR}"
-          echo $KUBE_SA_TOKEN
-          echo $VAULT_APP_ROLE
-          echo $KUBERNETES_AUTH_PATH
+
           # Login to Vault and so I can get an approle token
           VAULT_CLIENT_TOKEN=$(curl -sS --request POST ${VAULT_ADDR}/v1/auth/${KUBERNETES_AUTH_PATH}/login \
             -H "Content-Type: application/json" \
@@ -95,99 +93,99 @@ spec:
           fi 
 
           echo "Done checking for certificates in vault"
-      # containers:
-      # - name: generate-cryptomaterials
-      #   image: {{ $.Values.image.initContainerName }}
-      #   imagePullPolicy: Always
-      #   env:
-      #   - name: VAULT_ADDR
-      #     value: {{ $.Values.vault.address }}
-      #   - name: KUBERNETES_AUTH_PATH
-      #     value: {{ $.Values.vault.authpath }}
-      #   - name: VAULT_APP_ROLE
-      #     value: {{ $.Values.vault.role }}
-      #   - name: VAULT_PEER_SECRET_PREFIX
-      #     value: "{{ $.Values.vault.adminsecretprefix }}"
-      #   - name: VAULT_ORDERER_SECRET_PREFIX
-      #     value: "{{ $.Values.vault.orderersecretprefix }}"
-      #   - name: MOUNT_PATH
-      #     value: "/certcheck"
-      #   - name: GO_VERSION
-      #     value: "{{ $.Values.go.version }}"
-      #   - name: INSTALL_OS
-      #     value: "{{ $.Values.installOs }}"  
-      #   - name: INSTALL_ARCH
-      #     value: "{{ $.Values.installArch }}"  
-      #   - name: GO_ROOT_DIR
-      #     value: "{{ $.Values.vault.orderersecretprefix }}"          
-      #   - name: GETH_PASSFRASE
-      #     value: "{{ $.Values.peer.gethPassphrase }}"
-      #   - name: PEER_NAME
-      #     value: "{{ $.Values.peer.name }}"
-      #   - name: DB_USER
-      #     value: "demouser"
-      #   - name: DB_PASSWORD
-      #     value: "password"                                    
-      #   command: ["sh", "-c"]
-      #   args:
-      #   - |-
-      #     #!/usr/bin/env sh
-      #     validateVaultResponse () {
-      #       if echo ${2} | grep "errors"; then
-      #         echo "ERROR: unable to retrieve ${1}: ${2}"
-      #         exit 1
-      #       fi
-      #       if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
-      #       then
-      #         http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
-      #         --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" \
-      #         ${VAULT_ADDR}/v1/${vault_secret_key})
-      #         curl_response=$?
-      #         if test "$http_code" != "200" ; then
-      #             echo "Http response code from Vault - $http_code"
-      #             if test "$curl_response" != "0"; then
-      #                echo "Error: curl command failed with error code - $curl_response"
-      #                exit 1
-      #             fi
-      #         fi
-      #       fi
-      #     }
+      containers:
+      - name: generate-cryptomaterials
+        image: {{ $.Values.image.initContainerName }}
+        imagePullPolicy: Always
+        env:
+        - name: VAULT_ADDR
+          value: {{ $.Values.vault.address }}
+        - name: KUBERNETES_AUTH_PATH
+          value: {{ $.Values.vault.authpath }}
+        - name: VAULT_APP_ROLE
+          value: {{ $.Values.vault.role }}
+        - name: VAULT_PEER_SECRET_PREFIX
+          value: "{{ $.Values.vault.adminsecretprefix }}"
+        - name: VAULT_ORDERER_SECRET_PREFIX
+          value: "{{ $.Values.vault.orderersecretprefix }}"
+        - name: MOUNT_PATH
+          value: "/certcheck"
+        - name: GO_VERSION
+          value: "{{ $.Values.go.version }}"
+        - name: INSTALL_OS
+          value: "{{ $.Values.installOs }}"  
+        - name: INSTALL_ARCH
+          value: "{{ $.Values.installArch }}"  
+        - name: GO_ROOT_DIR
+          value: "{{ $.Values.vault.orderersecretprefix }}"          
+        - name: GETH_PASSFRASE
+          value: "{{ $.Values.peer.gethPassphrase }}"
+        - name: PEER_NAME
+          value: "{{ $.Values.peer.name }}"
+        - name: DB_USER
+          value: "demouser"
+        - name: DB_PASSWORD
+          value: "password"                                    
+        command: ["sh", "-c"]
+        args:
+        - |-
+          #!/usr/bin/env sh
+          validateVaultResponse () {
+            if echo ${2} | grep "errors"; then
+              echo "ERROR: unable to retrieve ${1}: ${2}"
+              exit 1
+            fi
+            if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
+            then
+              http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
+              --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" \
+              ${VAULT_ADDR}/v1/${vault_secret_key})
+              curl_response=$?
+              if test "$http_code" != "200" ; then
+                  echo "Http response code from Vault - $http_code"
+                  if test "$curl_response" != "0"; then
+                     echo "Error: curl command failed with error code - $curl_response"
+                     exit 1
+                  fi
+              fi
+            fi
+          }
 
-      #     if [ -e /certcheck/present.txt ]
-      #         then
-      #           echo "Certificates already present in the vault. Skipping.."
-      #           exit 0
-      #     fi
+          if [ -e /certcheck/present.txt ]
+              then
+                echo "Certificates already present in the vault. Skipping.."
+                exit 0
+          fi
 
-      #     echo "Go installation"
-      #     curl https://storage.googleapis.com/golang/go${GO_VERSION}.${INSTALL_OS}-${INSTALL_ARCH}.tar.gz
-      #     tar -zxf go${GO_VERSION}.${INSTALL_OS}-${INSTALL_ARCH}.tar.gz --directory "${GO_ROOT_DIR}"
-      #     cp -R "${GO_ROOT_DIR}/go/bin/go /bin"
-      #     export GOROOT="${GO_ROOT_DIR}"
+          echo "Go installation"
+          curl https://storage.googleapis.com/golang/go${GO_VERSION}.${INSTALL_OS}-${INSTALL_ARCH}.tar.gz
+          tar -zxf go${GO_VERSION}.${INSTALL_OS}-${INSTALL_ARCH}.tar.gz --directory "${GO_ROOT_DIR}"
+          cp -R "${GO_ROOT_DIR}/go/bin/go /bin"
+          export GOROOT="${GO_ROOT_DIR}"
 
-      #     echo "Geth installation"
-      #     mkdir -p /bin/quorum
-      #     curl -L -o /bin https://github.com/ConsenSys/quorum.git
-      #     make /bin/quorum geth
-      #     cp -R /bin/quorum/build/bin/geth /bin
+          echo "Geth installation"
+          mkdir -p /bin/quorum
+          curl -L -o /bin https://github.com/ConsenSys/quorum.git
+          make /bin/quorum geth
+          cp -R /bin/quorum/build/bin/geth /bin
 
-      #     echo "Bootnode installation"
-      #     make /bin/quorum bootnode
-      #     cp -R /bin/quorum/build/bin/bootnode /bin
+          echo "Bootnode installation"
+          make /bin/quorum bootnode
+          cp -R /bin/quorum/build/bin/bootnode /bin
             
-      #     echo "Creating files and certs"
-      #     /bin/bootnode --nodekey nodekey --writeaddress > enode
-      #     echo ${GETH_PASSFRASE} >> /password
-      #     /bin/geth account new --datadir ${PEER_NAME} --password password
-      #     cp keystore/* keystore.json
+          echo "Creating files and certs"
+          /bin/bootnode --nodekey nodekey --writeaddress > enode
+          echo ${GETH_PASSFRASE} >> /password
+          /bin/geth account new --datadir ${PEER_NAME} --password password
+          cp keystore/* keystore.json
 
-      #     #encode to base64 to update to vault otherwise json format is creating problems with vault api
-      #     nodekey_base64=$(cat nodeKey.key | base64 -w 0)
+          #encode to base64 to update to vault otherwise json format is creating problems with vault api
+          nodekey_base64=$(cat nodeKey.key | base64 -w 0)
 
-      #     echo "Saving files in vault"
-      #     curl -sS --request POST ${VAULT_ADDR}/v1/auth/${KUBERNETES_AUTH_PATH}/quorum \
-      #           -H "Content-Type: application/json" \
-      #           -d '{"nodekey":"'"$nodekey_base64"'","keystore":"'"$(cat keystore.json)"'","db_user":"'"${DB_USER}"'","db_password":"'"${DB_PASSWORD}"'","geth_password":"'"$(cat password)"'"}'
+          echo "Saving files in vault"
+          curl -sS --request POST ${VAULT_ADDR}/v1/auth/${KUBERNETES_AUTH_PATH}/quorum \
+                -H "Content-Type: application/json" \
+                -d '{"nodekey":"'"$nodekey_base64"'","keystore":"'"$(cat keystore.json)"'","db_user":"'"${DB_USER}"'","db_password":"'"${DB_PASSWORD}"'","geth_password":"'"$(cat password)"'"}'
       volumes:
         - name: certcheck
           emptyDir:
