Updated files
Signed-off-by: alvaropicazo <alvaro.picazo.haase@accenture.com>

diff --git a/platforms/quorum/charts/crypto_ibft/templates/job.yaml b/platforms/quorum/charts/crypto_ibft/templates/job.yaml
--- a/platforms/quorum/charts/crypto_ibft/templates/job.yaml
+++ b/platforms/quorum/charts/crypto_ibft/templates/job.yaml
@@ -1,10 +1,10 @@
 apiVersion: batch/v1
 kind: Job
 metadata:
-  name: {{ $.Values.metadata.name }}
-  namespace: {{ $.Values.metadata.namespace }}
+  name: "{{ $.Values.metadata.name }}"
+  namespace: "{{ $.Values.metadata.namespace }}"
   labels:
-    app: {{ $.Values.metadata.name }}
+    app: "{{ $.Values.metadata.name }}"
     app.kubernetes.io/name: cryptomanterial-ibft-{{ $.Values.peer.name }}
     helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
     app.kubernetes.io/managed-by: {{ .Release.Service }}
@@ -14,8 +14,8 @@ spec:
   template:
     metadata:
       labels:
-        app: {{ $.Values.metadata.name }}
-        app.kubernetes.io/name: {{ $.Values.metadata.name }}
+        app: "{{ $.Values.metadata.name }}"
+        app.kubernetes.io/name: "{{ $.Values.metadata.name }}"
         app.kubernetes.io/instance: {{ .Release.Name }}
     spec:
       restartPolicy: OnFailure
@@ -29,8 +29,8 @@ spec:
           emptyDir:
             medium: Memory
       initContainers:
-      - name: crypto-init
-        image: {{ $.Values.image.initContainerName }}
+      - name: "crypto-init"
+        image: "{{ $.Values.image.initContainerName }}"
         imagePullPolicy: Always
         env:
         - name: VAULT_ADDR
@@ -40,7 +40,7 @@ spec:
         - name: VAULT_APP_ROLE
           value: {{ $.Values.vault.role }}
         - name: CERTS_SECRET_PREFIX
-          value: {{ .Values.vault.certsecretprefix }}          
+          value: "{{ .Values.vault.certsecretprefix }}"        
         - name: MOUNT_PATH
           value: "/certcheck"
         - name: PEER_NAME
@@ -85,130 +85,132 @@ spec:
 
           mkdir -p ${MOUNT_PATH}
           LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/crypto/${PEER_NAME}/quorum | jq -r 'if .errors then . else . end')
-          touch ${MOUNT_PATH}/absent.txt
-          # if echo ${LOOKUP_SECRET_RESPONSE} | grep "errors"
-          # then
-          #   echo "Certificates absent in vault. Ignore error warning"
-          #   touch ${MOUNT_PATH}/absent.txt
-          # else 
-          #   checknodekey=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["keystore"]') 
-          #   if [ ! -z "$checknodekey" ]
-          #   then
-          #     echo "Certificates absent in vault. Ignore error warning"
-          #     touch ${MOUNT_PATH}/absent.txt
-          #   else
-          #     validateVaultResponse "${CERTS_SECRET_PREFIX}/crypto/${PEER_NAME}/quorum" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
-          #     echo "Certificates present in vault"
-          #     touch ${MOUNT_PATH}/present.txt
-          #   fi    
-          # fi 
+          echo  "Empezamos a ver"
+          echo $LOOKUP_SECRET_RESPONSE
+          #touch ${MOUNT_PATH}/absent.txt
+          if echo ${LOOKUP_SECRET_RESPONSE} | grep "errors"
+          then
+            echo "Certificates absent in vault. Ignore error warning"
+            touch ${MOUNT_PATH}/absent.txt
+          else 
+            checknodekey=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["keystore"]') 
+            if [ ! -z "$checknodekey" ]
+            then
+              echo "Certificates absent in vault. Ignore error warning"
+              touch ${MOUNT_PATH}/absent.txt
+            else
+              validateVaultResponse "${CERTS_SECRET_PREFIX}/crypto/${PEER_NAME}/quorum" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
+              echo "Certificates present in vault"
+              touch ${MOUNT_PATH}/present.txt
+            fi    
+          fi 
 
           echo "Done checking for certificates in vault"
-      containers:
-      - name: generate-cryptomaterials
-        image: {{ $.Values.image.node }}
-        imagePullPolicy: IfNotPresent
-        env:
-        - name: VAULT_ADDR
-          value: {{ $.Values.vault.address }}
-        - name: KUBERNETES_AUTH_PATH
-          value: {{ $.Values.vault.authpath }}
-        - name: VAULT_APP_ROLE
-          value: {{ $.Values.vault.role }}
-        - name: VAULT_PEER_SECRET_PREFIX
-          value: "{{ $.Values.vault.adminsecretprefix }}"
-        - name: VAULT_ORDERER_SECRET_PREFIX
-          value: "{{ $.Values.vault.orderersecretprefix }}"
-        - name: MOUNT_PATH
-          value: "/certcheck"
-        - name: GO_VERSION
-          value: "{{ $.Values.go.version }}"
-        - name: CERTS_SECRET_PREFIX
-          value: {{ .Values.vault.certsecretprefix }}               
-        - name: INSTALL_OS
-          value: "{{ $.Values.installOs }}"  
-        - name: INSTALL_ARCH
-          value: "{{ $.Values.installArch }}"  
-        - name: GO_ROOT_DIR
-          value: "{{ $.Values.go.rootDir }}"          
-        - name: GETH_PASSPHRASE
-          value: "{{ $.Values.peer.gethPassphrase }}"
-        - name: BIN_FOLDER
-          value: "{{ $.Values.bin_install_dir }}"
-        - name: PEER_NAME
-          value: "{{ $.Values.peer.name }}"
-        - name: DB_USER
-          value: "demouser"
-        - name: DB_PASSWORD
-          value: "password"                                    
-        command: ["/bin/bash", "-c"]
-        args:
-        - |-
-          apk update && apk add jq curl openssl;
-          validateVaultResponse () {
-            if echo ${2} | grep "errors"; then
-              echo "ERROR: unable to retrieve ${1}: ${2}"
-              exit 1
-            fi
-            if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
-            then
-              http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
-              --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" \
-              ${VAULT_ADDR}/v1/${vault_secret_key})
-              curl_response=$?
-              if test "$http_code" != "200" ; then
-                  echo "Http response code from Vault - $http_code"
-                  if test "$curl_response" != "0"; then
-                     echo "Error: curl command failed with error code - $curl_response"
-                     exit 1
-                  fi
-              fi
-            fi
-          }
+      # containers:
+      # - name: "generate-cryptomaterials"
+      #   image: "{{ $.Values.image.node }}"
+      #   imagePullPolicy: IfNotPresent
+      #   env:
+      #   - name: VAULT_ADDR
+      #     value: "{{ $.Values.vault.address }}"
+      #   - name: KUBERNETES_AUTH_PATH
+      #     value: {{ $.Values.vault.authpath }}
+      #   - name: VAULT_APP_ROLE
+      #     value: {{ $.Values.vault.role }}
+      #   - name: VAULT_PEER_SECRET_PREFIX
+      #     value: "{{ $.Values.vault.adminsecretprefix }}"
+      #   - name: VAULT_ORDERER_SECRET_PREFIX
+      #     value: "{{ $.Values.vault.orderersecretprefix }}"
+      #   - name: MOUNT_PATH
+      #     value: "/certcheck"
+      #   - name: GO_VERSION
+      #     value: "{{ $.Values.go.version }}"
+      #   - name: CERTS_SECRET_PREFIX
+      #     value: {{ .Values.vault.certsecretprefix }}               
+      #   - name: INSTALL_OS
+      #     value: "{{ $.Values.installOs }}"  
+      #   - name: INSTALL_ARCH
+      #     value: "{{ $.Values.installArch }}"  
+      #   - name: GO_ROOT_DIR
+      #     value: "{{ $.Values.go.rootDir }}"          
+      #   - name: GETH_PASSPHRASE
+      #     value: "{{ $.Values.peer.gethPassphrase }}"
+      #   - name: BIN_FOLDER
+      #     value: "{{ $.Values.bin_install_dir }}"
+      #   - name: PEER_NAME
+      #     value: "{{ $.Values.peer.name }}"
+      #   - name: DB_USER
+      #     value: "demouser"
+      #   - name: DB_PASSWORD
+      #     value: "password"                                    
+      #   command: ["/bin/bash", "-c"]
+      #   args:
+      #   - |-
+      #     apk update && apk add jq curl openssl;
+      #     validateVaultResponse () {
+      #       if echo ${2} | grep "errors"; then
+      #         echo "ERROR: unable to retrieve ${1}: ${2}"
+      #         exit 1
+      #       fi
+      #       if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
+      #       then
+      #         http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
+      #         --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" \
+      #         ${VAULT_ADDR}/v1/${vault_secret_key})
+      #         curl_response=$?
+      #         if test "$http_code" != "200" ; then
+      #             echo "Http response code from Vault - $http_code"
+      #             if test "$curl_response" != "0"; then
+      #                echo "Error: curl command failed with error code - $curl_response"
+      #                exit 1
+      #             fi
+      #         fi
+      #       fi
+      #     }
 
-          if [ -e /certcheck/present.txt ]
-              then
-                echo "Certificates already present in the vault. Skipping.."
-                exit 0
-          fi
-          echo "Fetching nodekey from vault"
+      #     if [ -e /certcheck/present.txt ]
+      #         then
+      #           echo "Certificates already present in the vault. Skipping.."
+      #           exit 0
+      #     fi
+      #     echo "Fetching nodekey from vault"
 
-          KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
-          echo "Getting secrets from Vault Server: ${VAULT_ADDR}"
+      #     KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
+      #     echo "Getting secrets from Vault Server: ${VAULT_ADDR}"
 
-          # Login to Vault and so I can get an approle token
-          VAULT_CLIENT_TOKEN=$(curl -sS --request POST ${VAULT_ADDR}/v1/auth/${KUBERNETES_AUTH_PATH}/login \
-            -H "Content-Type: application/json" \
-            -d '{"role":"'"${VAULT_APP_ROLE}"'","jwt":"'"${KUBE_SA_TOKEN}"'"}' | \
-            jq -r 'if .errors then . else .auth.client_token end')
-          validateVaultResponse 'vault login token' "${VAULT_CLIENT_TOKEN}"
+      #     # Login to Vault and so I can get an approle token
+      #     VAULT_CLIENT_TOKEN=$(curl -sS --request POST ${VAULT_ADDR}/v1/auth/${KUBERNETES_AUTH_PATH}/login \
+      #       -H "Content-Type: application/json" \
+      #       -d '{"role":"'"${VAULT_APP_ROLE}"'","jwt":"'"${KUBE_SA_TOKEN}"'"}' | \
+      #       jq -r 'if .errors then . else .auth.client_token end')
+      #     validateVaultResponse 'vault login token' "${VAULT_CLIENT_TOKEN}"
 
-          VAULT_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/crypto/${PEER_NAME}/quorum | jq -r 'if .errors then . else . end')
-          echo $VAULT_RESPONSE
-          nodekey=$(echo ${VAULT_RESPONSE} | jq -r '.data["nodekey"]')
-          echo $nodekey
-          echo "Creating files and certs"
-          echo $nodekey >> nodekey
-          echo $GETH_PASSPHRASE >> password
-          bootnode --nodekey nodekey --writeaddress >> enode
-          geth account new --datadir ${PEER_NAME} --password password
-          rm -r password
-          cp ${PEER_NAME}/keystore/* keystore
-          #echo $keystore
-          #base64 keystore > base64_keystore
-          base64_keystore=$(cat keystore | base64 -w 0)
-          #echo $base64_keystore
-          #openssl base64 -in keystore -out newcheckbase64
-          echo "AGAIN"
-          #echo $newcheckbase64
-          vault_secret_key="${CERTS_SECRET_PREFIX}/crypto/${PEER_NAME}/quorum"
-          # Save the generated keys to VAULT
-          tail -f /dev/null
-          SAVE_CERTS_RESPONSE=$(curl -sS -H "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" \
-            -H "Content-Type: application/json" \
-            -X POST \
-            -d '{"keystore":"'"$base64_keystore"'","db_user":"'"${DB_USER}"'","db_password":"'"${DB_PASSWORD}"'","geth_password":"'"${GETH_PASSPHRASE}"'"}' \
-            ${VAULT_ADDR}/v1/${vault_secret_key} )
-          echo $SAVE_CERTS_RESPONSE  
-          validateVaultResponse "secret (${vault_secret_key})" "${SAVE_CERTS_RESPONSE}" "SAVE_CERTS_RESPONSE"
-          echo "Termine"
+      #     VAULT_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/crypto/${PEER_NAME}/quorum | jq -r 'if .errors then . else . end')
+      #     echo $VAULT_RESPONSE
+      #     nodekey=$(echo ${VAULT_RESPONSE} | jq -r '.data["nodekey"]')
+      #     echo $nodekey
+      #     echo "Creating files and certs"
+      #     echo $nodekey >> nodekey
+      #     echo $GETH_PASSPHRASE >> password
+      #     bootnode --nodekey nodekey --writeaddress >> enode
+      #     geth account new --datadir ${PEER_NAME} --password password
+      #     rm -r password
+      #     cp ${PEER_NAME}/keystore/* keystore
+      #     #echo $keystore
+      #     #base64 keystore > base64_keystore
+      #     base64_keystore=$(cat keystore | base64 -w 0)
+      #     #echo $base64_keystore
+      #     #openssl base64 -in keystore -out newcheckbase64
+      #     echo "AGAIN"
+      #     #echo $newcheckbase64
+      #     vault_secret_key="${CERTS_SECRET_PREFIX}/crypto/${PEER_NAME}/quorum"
+      #     # Save the generated keys to VAULT
+      #     tail -f /dev/null
+      #     SAVE_CERTS_RESPONSE=$(curl -sS -H "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" \
+      #       -H "Content-Type: application/json" \
+      #       -X POST \
+      #       -d '{"keystore":"'"$base64_keystore"'","db_user":"'"${DB_USER}"'","db_password":"'"${DB_PASSWORD}"'","geth_password":"'"${GETH_PASSPHRASE}"'"}' \
+      #       ${VAULT_ADDR}/v1/${vault_secret_key} )
+      #     echo $SAVE_CERTS_RESPONSE  
+      #     validateVaultResponse "secret (${vault_secret_key})" "${SAVE_CERTS_RESPONSE}" "SAVE_CERTS_RESPONSE"
+      #     echo "Termine"
