[ci skip] Deleting gitops release files
Signed-off-by: alvaropicazo <alvaro.picazo.haase@accenture.com>

diff --git a/platforms/quorum/charts/crypto_ibft/templates/job.yaml b/platforms/quorum/charts/crypto_ibft/templates/job.yaml
--- a/platforms/quorum/charts/crypto_ibft/templates/job.yaml
+++ b/platforms/quorum/charts/crypto_ibft/templates/job.yaml
@@ -84,9 +84,6 @@ spec:
 
           mkdir -p ${MOUNT_PATH}
           LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/crypto/${PEER_NAME}/quorum | jq -r 'if .errors then . else . end')
-          echo  "Empezamos a ver"
-          echo $LOOKUP_SECRET_RESPONSE
-          #touch ${MOUNT_PATH}/absent.txt
           if echo ${LOOKUP_SECRET_RESPONSE} | grep "errors"
           then
             echo "Certificates absent in vault. Ignore error warning"
@@ -148,59 +145,59 @@ spec:
           apk update && apk add jq curl openssl;
           echo "We are in"
           tail -f /dev/null
-          # validateVaultResponse () {
-          #   if echo ${2} | grep "errors"; then
-          #     echo "ERROR: unable to retrieve ${1}: ${2}"
-          #     exit 1
-          #   fi
-          #   if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
-          #   then
-          #     http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
-          #     --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" \
-          #     ${VAULT_ADDR}/v1/${vault_secret_key})
-          #     curl_response=$?
-          #     if test "$http_code" != "200" ; then
-          #         echo "Http response code from Vault - $http_code"
-          #         if test "$curl_response" != "0"; then
-          #            echo "Error: curl command failed with error code - $curl_response"
-          #            exit 1
-          #         fi
-          #     fi
-          #   fi
-          # }
+          validateVaultResponse () {
+            if echo ${2} | grep "errors"; then
+              echo "ERROR: unable to retrieve ${1}: ${2}"
+              exit 1
+            fi
+            if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
+            then
+              http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
+              --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" \
+              ${VAULT_ADDR}/v1/${vault_secret_key})
+              curl_response=$?
+              if test "$http_code" != "200" ; then
+                  echo "Http response code from Vault - $http_code"
+                  if test "$curl_response" != "0"; then
+                     echo "Error: curl command failed with error code - $curl_response"
+                     exit 1
+                  fi
+              fi
+            fi
+          }
 
-          # if [ -e /certcheck/present.txt ]
-          #     then
-          #       echo "Certificates already present in the vault. Skipping.."
-          #       exit 0
-          # fi
-          # echo "Fetching nodekey from vault"
-          # tail -f /dev/null
-          # KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
-          # echo "Getting secrets from Vault Server: ${VAULT_ADDR}"
-          # # Login to Vault and so I can get an approle token
-          # VAULT_CLIENT_TOKEN=$(curl -sS --request POST ${VAULT_ADDR}/v1/auth/${KUBERNETES_AUTH_PATH}/login \
-          #   -H "Content-Type: application/json" \
-          #   -d '{"role":"'"${VAULT_APP_ROLE}"'","jwt":"'"${KUBE_SA_TOKEN}"'"}' | \
-          #   jq -r 'if .errors then . else .auth.client_token end')
-          # validateVaultResponse 'vault login token' "${VAULT_CLIENT_TOKEN}"
-          # VAULT_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/crypto/${PEER_NAME}/quorum | jq -r 'if .errors then . else . end')
-          # echo $VAULT_RESPONSE
-          # nodekey=$(echo ${VAULT_RESPONSE} | jq -r '.data["nodekey"]')
-          # echo "Creating files and certs"
-          # echo $nodekey >> nodekey
-          # echo $GETH_PASSPHRASE >> password
-          # bootnode --nodekey nodekey --writeaddress >> enode
-          # geth account new --datadir ${PEER_NAME} --password password
-          # cp ${PEER_NAME}/keystore/* keystorefile
-          # base64_keystore=$(cat keystorefile | base64 -w 0)
-          # vault_secret_key="${CERTS_SECRET_PREFIX}/crypto/${PEER_NAME}/quorum"
-          # # Save the generated keys to VAULT
-          # tail -f /dev/null
-          # LOOKUP_SECRET_RESPONSE=$(curl -sS -H "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" \
-          #   -H "Content-Type: application/json" \
-          #   -X POST \
-          #   -d '{"nodekey":"'"$nodekey"'","keystore":"'"$base64_keystore"'","db_user":"'"${DB_USER}"'","db_password":"'"${DB_PASSWORD}"'","geth_password":"'"${GETH_PASSPHRASE}"'"}' \
-          #   ${VAULT_ADDR}/v1/${vault_secret_key} | \
-          #   jq -r 'if .errors then . else .auth.client_token end')
-          # validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
+          if [ -e /certcheck/present.txt ]
+              then
+                echo "Certificates already present in the vault. Skipping.."
+                exit 0
+          fi
+          echo "Fetching nodekey from vault"
+          tail -f /dev/null
+          KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
+          echo "Getting secrets from Vault Server: ${VAULT_ADDR}"
+          # Login to Vault and so I can get an approle token
+          VAULT_CLIENT_TOKEN=$(curl -sS --request POST ${VAULT_ADDR}/v1/auth/${KUBERNETES_AUTH_PATH}/login \
+            -H "Content-Type: application/json" \
+            -d '{"role":"'"${VAULT_APP_ROLE}"'","jwt":"'"${KUBE_SA_TOKEN}"'"}' | \
+            jq -r 'if .errors then . else .auth.client_token end')
+          validateVaultResponse 'vault login token' "${VAULT_CLIENT_TOKEN}"
+          VAULT_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/crypto/${PEER_NAME}/quorum | jq -r 'if .errors then . else . end')
+          echo $VAULT_RESPONSE
+          nodekey=$(echo ${VAULT_RESPONSE} | jq -r '.data["nodekey"]')
+          echo "Creating files and certs"
+          echo $nodekey >> nodekey
+          echo $GETH_PASSPHRASE >> password
+          bootnode --nodekey nodekey --writeaddress >> enode
+          geth account new --datadir ${PEER_NAME} --password password
+          cp ${PEER_NAME}/keystore/* keystorefile
+          base64_keystore=$(cat keystorefile | base64 -w 0)
+          vault_secret_key="${CERTS_SECRET_PREFIX}/crypto/${PEER_NAME}/quorum"
+          # Save the generated keys to VAULT
+          tail -f /dev/null
+          LOOKUP_SECRET_RESPONSE=$(curl -sS -H "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" \
+            -H "Content-Type: application/json" \
+            -X POST \
+            -d '{"nodekey":"'"$nodekey"'","keystore":"'"$base64_keystore"'","db_user":"'"${DB_USER}"'","db_password":"'"${DB_PASSWORD}"'","geth_password":"'"${GETH_PASSPHRASE}"'"}' \
+            ${VAULT_ADDR}/v1/${vault_secret_key} | \
+            jq -r 'if .errors then . else .auth.client_token end')
+          validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
